# Generated by Django 4.2.10 on 2026-05-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField()),
                ('room_type', models.CharField(choices=[('amphi', 'Amphitheater'), ('class', 'Classroom'), ('lab', 'Lab/Workshop'), ('meeting', 'Meeting Room')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
