# Generated by Django 4.2.10 on 2026-05-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_remove_equipmentreservation_equipment_and_more'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='equipments',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='equipments.equipment'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('salle_cours', 'Salle de cours'), ('salle_td', 'Salle de TD'), ('salle_tp', 'Salle de TP'), ('salle_info', 'Salle Informatique'), ('amphi', 'Amphi'), ('labo', 'Labo'), ('atelier', 'Atelier'), ('salle_reunion', 'Salle de réunion'), ('bureau', 'Bureau'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type'], name='rooms_room_room_ty_632e38_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_available'], name='rooms_room_is_avai_ad8094_idx'),
        ),
    ]
