# Generated by Django 4.2.10 on 2026-05-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_equipments_alter_room_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
