# Generated by Django 4.2.10 on 2026-05-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentreservation',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
