# Generated by Django 4.2.10 on 2026-05-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_equipment_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentreservation',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='equipmentreservation',
            name='user',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['is_available'], name='equipments__is_avai_28d0fd_idx'),
        ),
        migrations.DeleteModel(
            name='EquipmentReservation',
        ),
    ]
