# Generated by Django 4.2.10 on 2026-05-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_remove_equipmentreservation_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
